# Generated by Django 5.1.1 on 2024-09-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_categories_created_at_categories_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
